/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.formularioenter;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class FormularioEnter extends javax.swing.JFrame {

    public int xMouse, yMouse;
    /**
     * Creates new form Login
     */
    public FormularioEnter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        whiteBg = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        passwordTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accederBtn = new javax.swing.JPanel();
        accederTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        whiteBg.setBackground(new java.awt.Color(255, 255, 255));
        whiteBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(255, 255, 255));
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        whiteBg.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 750, -1));

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.login-2.png"))); // NOI18N
        whiteBg.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, -1));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        whiteBg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, 10));

        passwordTxt.setForeground(new java.awt.Color(204, 204, 204));
        passwordTxt.setText("jPasswordField1");
        passwordTxt.setBorder(null);
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });
        passwordTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTxtMousePressed(evt);
            }
        });
        whiteBg.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, -1));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        whiteBg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, 20));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel1.setText("Usuario");
        whiteBg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setText("Contraseña");
        whiteBg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        accederBtn.setBackground(new java.awt.Color(153, 153, 255));
        accederBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accederBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accederBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accederBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accederBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accederBtnMouseReleased(evt);
            }
        });

        accederTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        accederTxt.setForeground(new java.awt.Color(255, 255, 255));
        accederTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accederTxt.setText("ACCEDER");

        javax.swing.GroupLayout accederBtnLayout = new javax.swing.GroupLayout(accederBtn);
        accederBtn.setLayout(accederBtnLayout);
        accederBtnLayout.setHorizontalGroup(
            accederBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accederBtnLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(accederTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        accederBtnLayout.setVerticalGroup(
            accederBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accederBtnLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(accederTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        whiteBg.add(accederBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 200, 40));

        emailTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(204, 204, 204));
        emailTxt.setText("mail@company.com");
        emailTxt.setToolTipText("");
        emailTxt.setBorder(null);
        emailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTxtFocusLost(evt);
            }
        });
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTxtMousePressed(evt);
            }
        });
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        whiteBg.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setText("INICIAR SESIÓN ");
        whiteBg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -400;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 54, 103, 84);
        jPanel1.add(whiteBg, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFocusLost
        // TODO add your handling code here:
        if(emailTxt.getText().isBlank()){
           emailTxt.setText("email@dominio.com");
           emailTxt.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_emailTxtFocusLost

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
        // TODO add your handling code here:
        if(String.valueOf(passwordTxt.getPassword()).isEmpty()){
           passwordTxt.setText("198723");
           passwordTxt.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_passwordTxtFocusLost

    private void accederBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederBtnMouseClicked
        // TODO add your handling code here:
        if(String.valueOf(passwordTxt.getPassword()).equals("123456" ) && emailTxt.getText().equals("michelle@gmail.com" )){
             JOptionPane.showMessageDialog(null, "¡Bienvenido al sistema!", "Inicio de sesión exitoso",
        JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "¡Error, verifica los datos!", "Error",
        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accederBtnMouseClicked

    private void emailTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMousePressed
        // TODO add your handling code here:
        emailTxt.setForeground(Color.black);
        emailTxt.setText("");
    }//GEN-LAST:event_emailTxtMousePressed

    private void passwordTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTxtMousePressed
        // TODO add your handling code here:
        passwordTxt.setForeground(Color.black);
        passwordTxt.setText(null);
    }//GEN-LAST:event_passwordTxtMousePressed

    private void accederBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederBtnMouseEntered
        // TODO add your handling code here:
         accederBtn.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_accederBtnMouseEntered

    private void accederBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederBtnMouseExited
        // TODO add your handling code here:
        accederBtn.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_accederBtnMouseExited

    private void accederBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederBtnMousePressed
        // TODO add your handling code here:
        accederBtn.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_accederBtnMousePressed

    private void accederBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederBtnMouseReleased
        // TODO add your handling code here:
        accederBtn.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_accederBtnMouseReleased

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_barraMouseDragged

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_emailTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEnter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioEnter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accederBtn;
    private javax.swing.JLabel accederTxt;
    private javax.swing.JPanel barra;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo2;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JPanel whiteBg;
    // End of variables declaration//GEN-END:variables
}
